### ISSUE TITLE
invalid value (nil) at index 2 in table for 'concat'

### ISSUE THREAD

**Issue by dobe0768** [hanxi/wlua#3]
function M.debug(...)
    if levels.debug < loglevel then return end
    local tbl = {}
    for i,v in pairs({...}) do
        if type(v) == "table" then
            tbl[i] = util_table.tostring(v)
        else
            tbl[i] = tostring(v)
        end
    end
    skynet.error("[DEBUG]", table.concat(tbl, " "))
end

 当里面tbl不是连续的会报错  
invalid value (nil) at index 2 in table for 'concat'

**Comment by hanxi** [comment]
> function M.debug(...) if levels.debug < loglevel then return end local tbl = {} for i,v in pairs({...}) do if type(v) == "table" then tbl[i] = util_table.tostring(v) else tbl[i] = tostring(v) end end skynet.error("[DEBUG]", table.concat(tbl, " ")) end
> 
> 当里面tbl不是连续的会报错 invalid value (nil) at index 2 in table for 'concat'

请问有完整的报错堆栈吗？

**Comment by dobe0768** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dobe0768** [comment]
昨天发现 今天没有重现出来  等再次出现我再贴出来
